### ISSUE TITLE
project_needle_pts.py script not working and throwing error

### ISSUE THREAD

**Issue by astitwlathe** [collaborative-robotics/surgical_robotics_challenge#29]
Hi Everyone,
When I try to run the [project_needle_pts.py script](https://github.com/collaborative-robotics/surgical_robotics_challenge/blob/master/scripts/surgical_robotics_challenge/examples/project_needle_pts.py), it throws an error:

OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/highgui/src/window.cpp, line 304
Traceback (most recent call last):
  File "project_needle_pts.py", line 125, in <module>
    cv2.imshow("img", img)
cv2.error: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/highgui/src/window.cpp:304: error: (-215) size.width>0 && size.height>0 in function imshow

The script seems to not be able to get images from ROS node. Thank you for your time.

**Comment by astitwlathe** [comment]
To add , I followed the link https://github.com/WPI-AIM/ambf/wiki/Camera-feed-and-depth-camera to resolve the error. However, the script does not work.

**Comment by adnanmunawar** [comment]
Can you go through this closed [issue](https://github.com/WPI-AIM/ambf/issues/155) and check all the points in the conversation.

**Comment by adnanmunawar** [comment]
Closing this as stale
