### ISSUE TITLE
Joint errors model 

### ISSUE THREAD

**Issue by nhatleminh1997** [collaborative-robotics/surgical_robotics_challenge#47]
I noticed that in line 72 file `joint_errors_model.py` for initializing joint error models
```
rand_val = 2. * random() - 1. 
```
will always give positive value for `rand_val` and therefore for the joint errors. I think you might want to flip the sign there.

**Comment by adnanmunawar** [comment]
Hi Nhat,

The range of `rand_val = 2. * random() - 1. ` should be between [`-1.0, 1.0`]. Checkout this snippet: https://onecompiler.com/python/3y24dpjhh

**Comment by nhatleminh1997** [comment]
You are right. I made a mistake while testing it.
