### ISSUE TITLE
ROS package source conflict

### ISSUE THREAD

**Issue by JackHaoyingZhou** [collaborative-robotics/surgical_robotics_challenge#60]
AMBF and rog_Geomagic are both required to be complied and please check the following figure of the error in the terminal. You can see that it will raise an error of not finding corresponding modules firstly. Nevertheless, when I source the AMBF package, the geomagic control package cannot be found.

I can solve it by temporarily adding the directory to sys.path, but probably you may have some better solutions. Therefore, would you mind letting me know your thoughts about how to solve it? Thanks!

![Selection_003](https://user-images.githubusercontent.com/36210531/204316471-aac4e6b5-5cde-4a77-8b39-a42a952c9648.png)

**Comment by adnanmunawar** [comment]
Hi Jack,

Thanks for explaining the issue. We have seen this kind of issue before where sourcing AMBF "unsources" other ROS workspaces and then sourcing the other ROS workspaces, "unsources" AMBF. What seems to have worked in the past is as follows:

In a terminal window

1. Remove AMBF's build folder (or clean it with rm -rf).
2. Source the ROS WS, (catkin_ws_geomagic) in your case.
3. Rebuild AMBF (i.e. cmake .. & make in AMBF's build folder).
4. Source AMBF. 

With this you should be able to have both AMBF and the ROS WS sourced and this should also work in new terminals windows.

**Comment by JackHaoyingZhou** [comment]
Thank you for the solution! The problem is resolved!
