### ISSUE TITLE
How to enable gravity compensation for MTM teleoperation control

### ISSUE THREAD

**Issue by JackHaoyingZhou** [collaborative-robotics/surgical_robotics_challenge#62]
Hi Adnan,

Hope all is well! 

I would like to ask about the instruction or hints about how to enable gravity compensation for MTM teleoperation control. Is there any method that we can use to enable gravity compensation for teleoperation control in AMBF?

Thank you and look forward to hearing from you!

**Comment by adnanmunawar** [comment]
Hi Jack, is this still an issue? We enable the gravity compensation for the real MTM in the [mtm_device_crtk](https://github.com/collaborative-robotics/surgical_robotics_challenge/blob/master/scripts/surgical_robotics_challenge/teleoperation/input_devices/mtm_device_crtk.p) at this [method](https://github.com/collaborative-robotics/surgical_robotics_challenge/blob/master/scripts/surgical_robotics_challenge/teleoperation/input_devices/mtm_device_crtk.py#L396). Essentially we publish to a topic called `/<MTM_TYPE>/use_gravity_compensation`.

**Comment by JackHaoyingZhou** [comment]
Hi Adnan, I think the problem is resolved. My original question is actually for PSM gravity compensation (PSM will stay still even the "mono" foot pedal button is not pressed).  Regarding to the MTM side, the gravity compensation can be activated through dVRK-ROS and can take the topic if required. For PSM side, since the gravity has been sat to 0, I would assume it is good to go.
